name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      - name: Authenticate DevHub
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY}}
 #     - name: Define CI org
 #       run: node_modules/sfdx-cli/bin/run force:org:create -v devhub -s -f config/project-scratch-def.json -a ciorg -d 1

 #     - name: Deploy source
 #       run: node_modules/sfdx-cli/bin/run force:source:push -u ciorg

#      - name: Run Apex test
#        run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Deploy To Environment
 #       run: |
 #         echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
 #         node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}}
 #         node_modules/sfdx-cli/bin/run force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername devhub --testlevel $TESTLEVEL
        run: |
          node_modules/sfdx-cli/bin/run force:mdapi:convert --rootdir force-app --outputdir codeDeploy
          node_modules/sfdx-cli/bin/run force:mdapi:deploy --wait 10 --deploydir codeDeploy --targetusername devhub --testlevel $TESTLEVEL

        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY}}
          DEPLOYDIR: src
          TESTLEVEL: RunLocalTests
