name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "10.x"
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      - name: Authenticate DevHub
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY}}
     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Deploy To Environment
        #       run: |
        #         echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        #         node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}}
        #         node_modules/sfdx-cli/bin/run force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername devhub --testlevel $TESTLEVEL
        # run: |
        #  node_modules/sfdx-cli/bin/run force:mdapi:convert --rootdir . --outputdir codeDeploy
        #  node_modules/sfdx-cli/bin/run force:mdapi:deploy --wait 10 --deploydir codeDeploy --targetusername devhub --testlevel $TESTLEVEL
        echo ${GITHUB_REF}
       
        run: node_modules/sfdx-cli/bin/run force:source:deploy --manifest ./manifest/package.xml -u devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY}}
          DEPLOYDIR: src
          TESTLEVEL: RunLocalTests

